# .github/workflows/example-workflow.yml

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Example step where the github-actions bot makes a git commit
        run: |
          # ...
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          # ...
